AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
    Default: call
  Stage:
    Type: String
    Description: Stage to deploy to
    Default: dev

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: !Ref Stage
      Variables:
        Stage: !Ref Stage

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: create_user/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /create-user
            Method: post
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /create-user
            Method: get

  CreateEvent:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: create_event/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /create-event
            Method: post

  ListEvents:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: list_events/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /list-events
            Method: get
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /list-events
            Method: post
  Subscribe:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: subscribe/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /subscribe
            Method: get
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /subscribe
            Method: post
  Notify:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: notify/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /notify
            Method: get
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /notify
            Method: post
  Poll:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: poll/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: production
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /poll
            Method: get
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /poll
            Method: post
